### PR TITLE
[+] .net core support (+ unit tests)

### PR DESCRIPTION
**Pull request by y-skindersky**
I have added .net standard as a target framework for core ZeroLog assembly and .net core app as a target framework for test assemblies. I have also remove several dependencies which are seems not used currently. Several dependencies were updated. Build script was modified to support build/test running under both .net framework 4.6 and .net core platforms. You may also require to replace NuGetPack with DotNetCorePack but I didn't change it. Could you please publish this version for testing purpose if possible? Thanks

### CODE REVIEW

**Comment by ablanchet** [comment]
Hi @y-skindersky, thanks for the PR. It looks clean to me. 
Updating NUnit to the latest version is something we should have done for a long time. On the other hand I'm not a big fan of [using the pre-release -rc06 version of NLog](https://github.com/Abc-Arbitrage/ZeroLog/pull/15/commits/b058a25a9b68b8d6f1a7712e22b43b0af91a8167#diff-b7141e725d285bbc23080f64d95c759dR54), I'd rather use the latest stable.

We already have [another open source library that targets .net standard ](https://github.com/disruptor-net/Disruptor-net). I'm wondering if we already did a clean version of the build file, and if it's possible to use the same (in order to maintain only one coherent build system). @ocoanet / @ltrzesniewski what do you think ?

We'll update the nuspec ([it still target net45](https://github.com/Abc-Arbitrage/ZeroLog/blob/master/build/ZeroLog.nuspec#L20)) and publish a new package on nuget when this PR will be merged, but in the meantime you can build a version on your own and test it.

**Comment by ltrzesniewski** [comment]
Thanks for this PR.

NLog is only used in the benchmarks project, so using a RC isn't an issue here. The project file looks bloated to me, as transitive package references don't need to be specified explicitly anymore with the new project file syntax. We should clean it up, but this it's not related to the PR and we'll do that separately.

Another thing: there are mixed tabs/spaces in this patch, and this needs to be normalized to spaces. We definitely should add an `.editorconfig` file to prevent this in the future.

**Comment by MendelMonteiro** [comment]
Package deployed: https://www.nuget.org/packages/ZeroLog/1.0.3.1

**Comment by rverdier** [comment]
@y-skindersky Thanks for the PR!

**Pull request merged**
