### PR TITLE
Update StringFormatter

### PR DESCRIPTION
**Pull request by ltrzesniewski**
There is a breaking change in `TimeSpan` formatting in this version, we need to decide how to handle the changes.

### CODE REVIEW

**Comment by ltrzesniewski** [comment]
This is related to https://github.com/MendelMonteiro/StringFormatter/pull/9.

There are a few issues I noticed:

- Negative `TimeSpan` values yield incorrect output
- The `format` parameter is passed as-is to the day counter formatter, which is wrong (it was ignored previously)
- Second fractions are now formatted as `.fffffff` instead of `.fff` (which is what that PR intended)

OTOH the previous version was badly broken, as the day count was never output.

See f5efb74043e153a98be8eda7fd6dcb8e6e527fe4 for examples of impacted usages.

I think we should implement some level of proper `TimeSpan` formatting support in StringFormatter. Maybe we should also default to `.fff` in ZeroLog to keep the existing behavior. Thoughts?

/cc @damageboy FYI

**Comment by damageboy** [comment]
Well, the "regular" `TimeSpan.ToString()` in CLR uses `.ffffff` formatting as well, which was one reason why I introduced the changes.

I think it makes sense to try and stay close to BCL formatting as much as possible, just for the sake of not having to think about defaults per library.

Do you consider changing default formatting changes in ZeroLog to be breaking changes?

**Comment by ltrzesniewski** [comment]
I agree that `.ffffff` makes sense for StringFormatter as a default, so it behaves like the BCL. That was a good change. :+1:

But I don't think it makes sense for the `%time` pattern, as it's much more precise than the available system clock resolution. I think the `%time` format should stay at `.fff`, which means we need some way to tell StringFormatter to behave that way or just roll our own formatting in `PrefixWriter`, which could easily be optimized as it's known to be between 0 and 24 hours. Maybe that's the better way to go.

I have no issues with defaulting to `.ffffff` for other appended timestamps, I'm only concerned with `%time` because it shows up at every line. I probably shouldn't call that a breaking change, it's rather a behavior change.

**Comment by damageboy** [comment]
I understand you point about the distinction between `%time` inside ZeroLog and default `TimeSpan` in StringFormatter.

The only I have to say is that system-clock accuracy / resolution is a complex topic, what follows is my understanding of the subject, and what I would personally go for, if it were me:

## Linux
The default system-clock source in Linux has no problem with providing sub microsecond resolution for the default time "system-calls" (I put that in double quotes since they aren't even real system calls, but instead uses the Linux [vDSO](http://man7.org/linux/man-pages/man7/vdso.7.html) mechanism).

Basically, on any system with a constant/invariant TSC, the default fake system call `clock_gettime()` will give you nano-second resolution timestamps, and for the most part, `Stopwatch.GetTimeStamp()` will map to that "system-call".

## Windows
As for windows, the generic time-stamp mechanism is not as accurate as Linux, but `Stopwatch.GetTimeStamp` (or more important `Stopwatch.Frequency`) actually IS accurate enough:
On my nearest Windows box:
```
> Stopwatch.Frequency
10000000
```
So the `Stopwatch` ticks are actually in 100ns ticks.

Also, very similarly to Linux vDSO, `Stopwatch.GetTimeStamp()` translates on most modern Windows machines to [`NtQueryPerformanceCounter`](https://docs.microsoft.com/en-us/windows/desktop/devnotes/ntqueryperformancecounter) which in-turn is normally completed in user-space inside `NTDLL.DLL` by calling [`RDTSC`](https://docs.microsoft.com/en-us/cpp/intrinsics/rdtsc?view=vs-2019) and dividing it by some magic number...

I guess what I'm trying to say, is that time-stamp resolution can and probably should be better (as a default) than milliseconds, and a microsecond resolution does sound like a sane default for ZeroLog in my opinion.

Moreover, if you switch ZeroLog to using the "correct" system-clock source per operating system, you can actually, and quite uniquely, kill two birds with one stone by:
* Eliminating system-calls (On Windows), while,
* Also getting better resolution...

It's entirely possible to make ZeroLog get microsecond level time-stamps with less overhead than what you are *probably* paying these days...

**Comment by ltrzesniewski** [comment]
I see, but then we'd have to translate `Stopwatch.GetTimeStamp()` to get the real time, which feels wrong as `Stopwatch` was designed to measure time intervals, not to get the absolute time. It could be hard to get right as the system time can be adjusted by NTP/PTP and we'd need to account for that.

Right now ZeroLog uses [`GetSystemTimePreciseAsFileTime`](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) on Windows. The docs say the following:

> The GetSystemTimePreciseAsFileTime function retrieves the current system date and time with the highest possible level of precision (<1us)

Which would suggest we already could use `.ffffff` by default for `%time`. I'll run a few tests.

Right now we're always using P/Invoke to get the timestamp (which is costly). We should replace that with `DateTime.UtcNow` on .NET Core which calls the same `GetSystemTimePreciseAsFileTime` function under the hood.

**Comment by MendelMonteiro** [comment]
I'm for falling back to the default StringFormatter timespan format and thus increasing the precision of the `%time` pattern.  I don't see any reason to limit ourselves for the sake of 4 chars per line.

Also, I don't think tooling should rely on the number of chars that are used to represent the date/time so I agree that this isn't really a breaking change.

**Comment by ltrzesniewski** [comment]
Shouldn't the default `TimeSpan` format in StringFormatter be `c` instead of `G` like in the frameowk? ([docs](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-timespan-format-strings)) ?

```
> TimeSpan.FromSeconds(42).ToString()
"00:00:42"
> TimeSpan.FromSeconds(42.42).ToString()
"00:00:42.4200000"
```

Also, for some reason, the day separator is `.` in the `c` format and `:` in `g` and `G`:

```
> TimeSpan.FromHours(42).ToString("c")
"1.18:00:00"
> TimeSpan.FromHours(42).ToString("g")
"1:18:00:00"
```

**Comment by ltrzesniewski** [comment]
=> https://github.com/MendelMonteiro/StringFormatter/pull/14

`c` is a bit annoying for `%time` in that it won't output the `.fffffff` part if it lands on a whole second, but it's pretty unlikely to happen, so I think we can just ignore it.

**Pull request merged**
