### PR TITLE
Fix issue #34

### PR DESCRIPTION
**Pull request by Sergei-Y**
Fix [issue #34](https://github.com/Abc-Arbitrage/ZeroLog/issues/34)
If the configuration contains a simple type name of an appender then the behaviour remains the same - zerolog searches the type in the current domain. But if the configuration contains an assembly-qualified type name of the appender zerolog tries to instantiate the type using .net type resolving mechanism. The code does not suppresses exceptions to simplify analysis in case when the type failed to instantiate.

### CODE REVIEW

**Comment by ltrzesniewski** [comment]
Thanks! Could you also add a unit test for this?
(Just create a dummy appender in the tests assembly and verify that it it's resolved correctly)

**Comment by Sergei-Y** [comment]
Yes, will do.

**Comment by ltrzesniewski** [comment]
Thanks! This is deployed in v1.4.2.

**Comment by Sergei-Y** [comment]
Great, thank you!

**Pull request merged**
