### PR TITLE
Add option to not use Console.OutputEncoding when using the ConsoleAppender

### LINKED ISSUE #60: Following program causes garbage collection
````

using ZeroLog;
using ZeroLog.Appenders;
using ZeroLog.Configuration;

LogManager.Initialize(new ZeroLogConfiguration()
{
    LogMessagePoolSize = 10240,
    RootLogger =
    {
        Appenders =
        {
            new ConsoleAppender()
        }
    }
});

var logger = LogManager.GetLogger("Main");

var rand = new Random();
while (true)
{
    var r = rand.Next();
    Thread.Sleep(100);
    logger.Info($"rand: {r}");
}
````

when running the above program using 2.0.1 nuget package of ZeroLog, I can see the system is doing garbage collection.

Maybe I'm misunderstanding what is going on, but I thought that the logging was meant to be zero allocation and thus no garbage should be created.

### PR DESCRIPTION
**Pull request by MendelMonteiro**
Fixes #60

### CODE REVIEW

**Comment by alexandrekow** [comment]
As seen with @MendelMonteiro we think using the default UTF8 encoding is good enough for most cases. 
It has the advantage of not allocating which is the goal of the library and do not add a new parameter. 
Let us know what you think @ltrzesniewski.

**Comment by MendelMonteiro** [comment]
@ltrzesniewski is there any reason in the end to support encodings other than UTF8?

**Comment by ltrzesniewski** [comment]
Not everyone speaks English 🙂 

Which console output would you rather see? `Console.OutputEncoding` vs `Encoding.UTF8`:

image

**Comment by ltrzesniewski** [comment]
Interestingly, you *can* change the console encoding on Windows, but I don't think a logging library should manipulate this setting.

```csharp
using var stream = Console.OpenStandardOutput();

const string message = "Salut, ça va?\r\n\r\n";

stream.Write(Console.OutputEncoding.GetBytes(message));
stream.Write(Encoding.UTF8.GetBytes(message));

Console.OutputEncoding = Encoding.UTF8;
stream.Write(Encoding.UTF8.GetBytes(message));
```

**Pull request closed without merging**
