### PR TITLE
Support logging unmanaged objects

### PR DESCRIPTION
**Pull request by scottstephens**
This pull request adds support for logging arbitrary unmanaged objects. By unmanaged I mean that the type of the object can satisfy the "unmanaged" generic constraint introduced in C# 7.3 (see https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters#unmanaged-constraint).

The basic usage is to 

- register a type using one of the `LogManager.RegisterUnmanaged<T>` methods
-  log using one of the `ILogEvent.AppendUnmanaged<T>` methods (the StringBuilder-like API)

Unfortunately I could not figure out a way to get the log4net-like API to work with unmanaged types.

If the type implements the `IStringFormattable` interface from the StringBuilder package then the version of `LogManager.RegisterUnmanaged<T>` with no arguments can be used. If the type doesn't implement that interface or a different format is desired for logging, the form of `LogManager.RegisterUnmanaged<T>` with one argument takes a delegate that does the actual formatting. Unregistered unmanaged types are logged as hex so that a meaningful (though not very user friendly) representation is logged in the event registration is forgotten.

Since the log4net-like API doesn't work with unmanaged objects, I found myself missing the ability to use format strings with the StringBuilder-like API. I've added that capability with the `ILogEvent.AppendF` method. I wasn't sure about the best name for this as the more natural choice collides with `IInternalLogEvent.AppendFormat`. The other options I considered were 

1. Use `ILogEvent.AppendFormat` and have `LogEvent` implement it explicitly.
2. Use `ILogEvent.AppendFormat` and have `LogEvent` implement `IInternalLogEvent.AppendFormat` explicitly.
3. Use `ILogEvent.AppendFormat` and rename `IInternalLogEvent.AppendFormat` to `IInternalLogEvent.AppendFormatInternal`.
4. Use another non-conflicting name, perhaps `ILogEvent.Format`.
5. Use `ILogEvent.AppendFormat` and get rid of `IInternalLogEvent.AppendFormat`; use `ILogEvent.AppendFormat` where `IInternalLogEvent.AppendFormat` is currently used. (The only difference is `ILogEvent.AppendF` returns the `ILogEvent` to enable the fluent API.)

Of these, I personally prefer option 3, but went with the AppendF approach since it was least intrusive to the existing codebase. Happy to change this if the maintainers have a preference.

### CODE REVIEW

**Comment by ltrzesniewski** [comment]
Thanks for this! We'll take a look.

**Comment by ltrzesniewski** [comment]
We didn't want to expose the `AppendFormat` method because it wouldn't be a very friendly API: you need to know you have to append the format first, followed by its arguments. So we removed `AppendF` and added unmanaged object support to the log4net-like API instead (which required to bypass the type system rules using custom IL). Let's say it's option 6 😄

**Comment by rverdier** [comment]
Thanks for your PR!

**Comment by scottstephens** [comment]
Your changes look good to me. I agree that supporting unmanaged types in the log4net-like API removes the need for AppendF.

**Comment by scottstephens** [comment]
I just realized your solution for the log4net-like API can't work with unmanaged objects passed by ref, which makes me more inclined to keep the AppendF functionality. Is knowing that you need to make an append call corresponding to each of your format string placeholders really that different from knowing that you need to add arguments to your InfoFormat call corresponding to each of your format string placeholders?

**Comment by MendelMonteiro** [comment]
I agree that matching calls to `AppendF` is as brittle as matching the placeholders in `InfoFormat`.  I would suggest using the `Info().Append().Log()` methods instead as it's more explicit.

The only thing missing is custom format specifiers which are currently not available for the unmanaged struct methods but can easily be added.

**Comment by ltrzesniewski** [comment]
Here's what I'm going to do:

 - Add `AppendUnmanaged` overloads with format specifiers
 - Generate `AppendUnmanaged` from a T4 template, as the code duplication will get out of control otherwise
 - Add support for nullable unmanaged types from the log4net-like API

**Comment by ltrzesniewski** [comment]
/azp run

(PR triggers were disabled for some reason, I enabled them)
(I still have to add nullable unmanaged types support to the log4net-like API, I'll do that tomorrow)

**Comment by ltrzesniewski** [comment]
Ok I think we're done here.

Here's a recap of the changes:

 - We now have lots of overloads of `AppendUnmanaged`, which is the "fast API". It includes byref overloads to avoid copies, and supports nullable types and formatting.
 - The "log4net-like" API supports unmanaged types, along with the nullable variant and formatting strings.
 - A few things were renamed
 - The `LogManager.RegisterUnmanaged(Type)` overload was added
 - Some implementation details were changed

@scottstephens does this look good for you?

**Comment by scottstephens** [comment]
Looks good to me!

**Comment by MendelMonteiro** [comment]
@scottstephens, we've released a new nuget package here: https://www.nuget.org/packages/ZeroLog/1.4.0

**Pull request merged**
